language: c
os: linux
dist: bionic
env:
- COLUMNS=78
before_install:
- sudo apt update
- sudo apt install -y python3 perl texinfo texlive libgsl-dev libgtk-3-dev libgtksourceview-3.0-dev
- sudo apt install -y pkg-config
- ./ci/prepare.sh
- ./ci/buildssw.sh
script:
- ./ci/buildpspp-linux.sh
